apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: kube-example
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
      targetPort: dbport
  selector:
    app: wordpress
    tier: mysql
---
apiVersion: apps/v1
kind: Deployment            # 资源类型 Deployment
metadata:
  name: wordpress-mysql     # 创建的 Deployment 名称为 wordpress-mysql
  namespace: kube-example   # 创建的 Deployment 属于 kube-example 命名空间
  labels:                   # 创建的 Deployment 标签 app: wordpress, tier: mysql
    app: wordpress
    tier: mysql
spec:
  selector:
    matchLabels:            # 匹配 标签为 app: wordpress,tier: mysql 的容器, 并管理这些容器
      app: wordpress
      tier: mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
        - name: mysql                     # 第二个容器名称 mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent   # 设置本地存在镜像就不去更新
          args: # 新版本镜像有更新，需要使用下面的认证插件环境变量配置才会生效
            - --default_authentication_plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          ports:
            - containerPort: 3306
              name: dbport
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootPassW0rd
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: wordpress
            - name: MYSQL_PASSWORD
              value: wordpress