# 定义PVC，用于消费PV
apiVersion: v1
kind: PersistentVolumeClaim   # 类型
metadata:
  name: host-path-pvc          # PVC的名称
spec:
  storageClassName: manual
  accessModes:                # 访问模式
    - ReadWriteOnce           # PVC以read-write挂载到一个节点
  resources:
    requests:
      storage: 1Gi            # PVC允许申请的大小