apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:  # 必须满足的条件
        nodeSelectorTerms:
          - matchExpressions:                          # 匹配规则 key是beta.kubernetes.io/arch, value中包含amd64
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                  - amd64
      preferredDuringSchedulingIgnoredDuringExecution:  # 期望满足的条件
        - weight: 1
          preference:
            matchExpressions:
              - key: disk-type
                operator: In
                values:
                  - ssd
  containers:
    - name: with-node-affinity
      image: gcr.io/google_containers/pause:2.0
