apiVersion: v1
kind: Namespace       # 资源类型
metadata:
  name: ngx-namespace  # 命名空间名称 ngx-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: ngx-pod
  namespace: ngx-namespace # 在 ngx-namespace 名称空间运行 Pod
spec:
  containers:
    - image: nginx:alpine
      name: ngx
      ports:
        - containerPort: 80

# Namespace 是 Kubernetes 项目里的一个逻辑管理单位。不同 Namespace 的 API 对象，在通过 kubectl 命令进行操作的时候，是互相隔离开的。
# 当然，这仅限于逻辑上的“隔离”，Namespace 并不会提供任何实际的隔离或者多租户能力。