apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcp
spec:
  containers:
    - name: liveness
      image: test-container:v1
      livenessProbe:
        tcpSocket:              # 存活探针 httpGet 类型，通过建立 TCP 连接来检查容器的健康状态。
          host: 10.2.0.2
          port: 8080            # 指定容器内接收探测请求的端口号为8080
        initialDelaySeconds: 5  # 第一次执行探针的时候要等待5秒
        periodSeconds: 5        # 每隔5秒执行一次存活探针
        timeoutSeconds: 5       # 探测超时，到了超时时间探测还没返回结果说明失败
        successThreshold: 1     # 成功阈值，连续几次成才算成功
        failureThreshold: 3     # 失败阈值，连续几次失败才算真失败