apiVersion: v1                  #k8sApi版本 kubectl api-resource 可以获取
kind: Pod                       #资源类型
metadata:                       #元数据:名称，命名空间，标签等
  name: ngx-pod                 #service的名称
  labels:                       #自定义标签属性列表
    env: demo
    owner: zcw
spec:                           #期望状态：详细描述pod容器，卷等
  containers:
    - image: nginx:alpine       #镜像地址
      name: ngx                 #镜像名称
      command:                  #执行命令,定义后会覆盖 Dockerfile 中的 CMD,ENTRYPOINT 命令
        - /bin/sh
        - -c
        - "echo ngx-container;sleep 3600;"
      ports:
        - containerPort: 80     #端口