apiVersion: v1                  #k8sApi版本 kubectl api-resource 可以获取
kind: Pod                       #资源类型
# 以上为type信息
metadata:                       #元数据:名称，命名空间，标签等
  name: ngx-pod                 #service的名称
  labels:                       #自定义标签属性列表
    env: demo
    owner: zcw
# 以上为元数据部分
spec:                           #期望状态：详细描述pod容器，卷等
  containers:
    - image: nginx:alpine       #镜像地址
      name: ngx                 #镜像名称
      ports:
        - containerPort: 80     #端口
# 以上为资源规格描述部分