apiVersion: v1                  #版本
kind: Pod                       #资源类型
metadata:                       #元数据
  name: wp-pod               #service的名称
  labels:                       #自定义标签属性列表
    app: wordpress
    role: website
spec:                           #详细描述
  containers:
    - image: wordpress:5         #镜像地址
      name: wp-pod               #镜像名称
      ports:
        - containerPort: 80   #端口
      envFrom:
        - prefix: 'WORDPRESS_DB_'
          configMapRef:
            name: wp-cm