apiVersion: v1
kind: Pod
metadata:
  name: ps-tcp-socket
spec:
  containers:
    - name: post-start-tcp-socket
      image: nginx:alpine
      lifecycle:
        postStart:    # 容器创建后立即执行
          tcpSocket:
            host: 10.0.0.2
            port: 8080