apiVersion: v1
kind: Pod
metadata:
  name: pre-stop
spec:
  volumes:
    - name: message
      hostPath:
        path: /tmp
  containers:
    - name: pre-stop
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: message
          mountPath: /usr/share/
      lifecycle:
        preStop:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "echo Hello from the postStart handler > /usr/share/message"
#          httpGet:
#            host: 10.0.0.2
#            httpHeaders:
#              - name: xx
#                value: xx
#            path: /
#            port: 8080
#          tcpSocket:
#            host: 10.0.0.2
#            port: 8080
