apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-pre-stop-demo
spec:
  volumes:
    - name: message
      hostPath:
        path: /tmp
  containers:
    - name: lifecycle-pre-stop-preStop
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: message
          mountPath: /usr/share/
      lifecycle:
        preStop:
          exec:
            command: ['/bin/sh', '-c', 'echo Hello from the preStop Handler > /usr/share/message']
