# env-config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-app-vars  # 定义名称为cm-app-vars的configMap获取值
data:
  appLogLevel: info     # key=appLogLevel, value=info
  appDataDir: /var/data # key=appDataDir, value=/var/data
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-test-pod
spec:
  containers:
    - name: cm-test-env
      image: busybox:1.28
      command: ["/bin/sh","-c","env | grep APP"]
      env:
        - name: APP_LOG_LEVEL       # 定义环境变量
          valueFrom:
            configMapKeyRef:        # 通过引用configMap获取值
              name: cm-app-vars
              key: appLogLevel      # 获取cm-appVars中key=appDataDir的值
        - name: APP_DATA_DIR
          valueFrom:
            configMapKeyRef:
              name: cm-app-vars
              key: appDataDir       # 获取cm-appVars中key=appDataDir的值


