apiVersion: v1
kind: Pod
metadata:
  name: pod-node-selector
spec:
  containers:
    - name: pod-node-selector
      image: busybox:1.28
      command: ["sleep", "3600"]
  nodeSelector:
    node-role.kubernetes.io/master: "k8s-node01" # 该Pod只会调度到node01节点上