apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
spec:
  completions: 5 # 希望pod运行的次数
  parallelism: 2 # 最大pod并行运行数量
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: counter
          image: busybox
          command:
            - "bin/sh"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1; do echo $i; done"

# ttlSecondsAfterFinished
# activeDeadlineSeconds 设置最大运行时间