apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-deployment
spec:
  selector:
    matchLabels:
      run: hpa-pod
  replicas: 1
  template:
    metadata:
      labels:
        run: hpa-pod
    spec:
      containers:
        - name: hpa-php
          image: hpa-php:test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 400m
            requests:
              cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: hpa-deployment-service
  labels:
    run: hpa-deployment-service
spec:
  ports:
    - port: 80
  selector:
    run: hpa-php

# kubectl autoscale deployment php --cpu-percent=50 --min=1 --max=10