apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-appVars  # 定义名称为cm-appVars的configMap获取值
data:
  appLogLevel: info     # key=appLogLevel, value=info
  appDataDir: /var/data # key=appDataDir, value=/var/data

