apiVersion: v1
kind: Pod
metadata:
  name: cm-test-pod
spec:
  containers:
    - name: cm-test
      image: busybox
      command: ["/bin/sh","-c","env | grep APP"]
      env:
        - name: APP_LOG_LEVEL       # 定义环境变量
          valueFrom:
            configMapKeyRef:        # 通过引用configMap获取值
              key: appLogLevel      # 获取cm-appVars中key=appDataDir的值
              name: cm-appVars
        - name: APP_DATA_DIR
          valueFrom:
            configMapKeyRef:
              key: appDataDir       # 获取cm-appVars中key=appDataDir的值
              name: cm-appVars

