apiVersion: v1
kind: Pod
metadata:
  name: cm-test-app
spec:
  containers:
    - name: cm-test-app
      image: kubeguide/tomcat-app:v1
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: server-xml              # 引用名称为server-xml的volume
          mountPath: /config-files      # 挂载到容器的目录
  volumes:
    - name: server-xml                  # 定义volume的名称
      configMap:                        # volume的值引用configMap
        name: cm-app-config-files       # 引用名称为cm-app-config-files的configMap
        items:
          - key: key-server-xml         # 引用的key
            path: server.xml            # 映射key为key-server-xml的值到文件server.xml
          - key: key-logging-properties # 引用的key
            path: logging.properties    # 映射key为key-logging-properties的值到文件logging.properties
