apiVersion: v1
kind: Pod
metadata:
  name: cm-test-app
spec:
  containers:
    - name: cm-test-app
      image: kubeguide/tomcat-app:v1
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: server-xml
          mountPath: /config-files
  volumes:
    - name: server-xml
      configMap:
        name: cm-app-config-files
