apiVersion: v1
kind: Service
metadata:
  name: pgpool-svc-external
spec:
  type: NodePort
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
      nodePort: 32000
  selector:
    app: pgpool
